name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
    # 以下のブランチにプッシュされた際起動
    push:
        branches: ["github-actions-test"]
    # Githubより手動で起動
    workflow_dispatch:

# env:
#     AAA: bbb

jobs:
  GitHub-Actions-Test:
    runs-on: ubuntu-22.04

    env:
        MONGO_INITDB_ROOT_USERNAME: root_user
        MONGO_INITDB_ROOT_PASSWORD: password
        BROWNIE_ATELIER_MONGO__MONGO_USE_DB: test_crawler_db
        BROWNIE_ATELIER_MONGO__MONGO_USER: common_user
        BROWNIE_ATELIER_MONGO__MONGO_PASS: password

    steps:
        # "🎉 ジョブはプッシュ イベントによって自動的にトリガーされました。" 
      - run: echo "🎉 起動したイベントの種類： ${{ github.event_name }}"
        # 「🐧 このジョブは現在、GitHub によってホストされている Linux サーバーで実行されています!」
      - run: echo "🐧 github上のOSの種類： ${{ runner.os }}"
        # "🔎 ブランチの名前は refs/heads/github-actions-test、リポジトリは pubranko/BrownieAtelier です。" を実行します。
      - run: echo "🔎 リポジトリ名： ${{ github.repository }}."
      - run: echo "🔎 ブランチ名： ${{ github.ref }}"
        # 上記のリポジトリ・ブランチにチェックアウト
      - name: 上記リポジトリ・ブランチにチェックアウト
        uses: actions/checkout@v4

        # 🖥️ ワークフローはランナーでコードをテストする準備ができました。」
      - run: echo "🖥️ ワークフローはランナーでコードをテストする準備ができました。"
        # 
      - name: リポジトリをクローンで格納した結果を確認
        # クローン後はここにソースが格納される /home/runner/work/BrownieAtelier/BrownieAtelier
        run: |
          ls -a ${{ github.workspace }}
        # "🍏 This job's status is success."
      - run: echo "🍏 実行後のステータス： ${{ job.status }}."

      # インストールされているものの一覧を調べてみた。
      #- run: sudo apt list --installed
      #- run: sudo dpkg-query -l

      - name: Start MongoDB
        run:  >
          docker run -d
          --name mongo-container
          -p 27017:27017
          -v $PWD/mongodb/init/create-user.js:/docker-entrypoint-initdb.d/create-user.js
          -e MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
          -e MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
          -e BROWNIE_ATELIER_MONGO__MONGO_USE_DB=${BROWNIE_ATELIER_MONGO__MONGO_USE_DB}
          -e BROWNIE_ATELIER_MONGO__MONGO_USER=${BROWNIE_ATELIER_MONGO__MONGO_USER}
          -e BROWNIE_ATELIER_MONGO__MONGO_PASS=${BROWNIE_ATELIER_MONGO__MONGO_PASS}
          mongo:7.0.1-jammy

      # - run: sleep 30

      - run: docker ps -a

      - run: docker stop mongo-container

      - run: sleep 10

      - run: docker ps -a

