name: Mongo container up
run-name: Mongo container up (ブランチ名:${{ github.ref }}) (ハッシュ値:${{ github.sha }})
on: 
    # 他のフローより呼び出し
    workflow_call:
        inputs:
            docker-network: 
              # ex) "--network sample-net"
              type: string
              required: false
            path_cache: 
              # ex) "/tmp/docker-img-arch"
              type: string
              required: false
            mongo_tag: 
              # ex) "7.0.1-jammy"
              type: string
              required: false
            
        #   image-name:
        #     type: string
        #     required: true
        #   cluster-name:
        #     type: string
        #     required: true
        #   service-name:
        #     type: string
        #     required: true
        # secrets:
        #   sample-secret-value:
        #     required: true    
    # Githubより手動で起動
    workflow_dispatch:

jobs:
  Prefect-Flow-Test:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "🎉 起動イベントの種類 (${{ github.event_name }})"

      - name: dockerネットワークをテスト用に作成
        # dockerネットワークを作成
        run: docker network create brownie-atelier-net

      - name: mongoDB用キャッシュID の定義
        # キャッシュID の定義
        id: mongo_image_cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.path_cache }}
          key: ${{ runner.os }}-mongo-${{ inputs.mongo_tag }}

      - name: mongoDBのイメージがキャッシュにない場合にpullとsave(キャッシュ)を実行
          # キャッシュ ID の作成
        if: steps.mongo_image_cache.outputs.cache-hit != 'true'
        run: |
          docker pull mongo:${{ inputs.mongo_tag }}
          docker save mongo:${{ inputs.mongo_tag }} -o ${{ inputs.path_cache }}
          ls -l ${{ inputs.path_cache }}
          docker images

      - name: キャッシュからmongoDBイメージを復元
        # キャッシュからmongoDBイメージを復元
        run: |
          docker load -i ${{ inputs.path_cache }}
          docker images

      - name: テスト用MongoDBコンテナー起動
        # mongoDBコンテナーの作成。
        #   rootユーザー、使用DB名を指定。
        #   一般ユーザーをcreate-user.jsで自動作成。
        run:  >
          docker run -d
          --name mongo-server
          -p 27017:27017
          ${{ inputs.docker-network }}
          -v $PWD/mongodb/init/create-user.js:/docker-entrypoint-initdb.d/create-user.js
          -e MONGO_INITDB_ROOT_USERNAME=${BROWNIE_ATELIER_MONGO__MONGO_INITDB_ROOT_USERNAME}
          -e MONGO_INITDB_ROOT_PASSWORD=${BROWNIE_ATELIER_MONGO__MONGO_INITDB_ROOT_PASSWORD}
          -e BROWNIE_ATELIER_MONGO__MONGO_USE_DB=${BROWNIE_ATELIER_MONGO__MONGO_USE_DB}
          -e BROWNIE_ATELIER_MONGO__MONGO_USER=${BROWNIE_ATELIER_MONGO__MONGO_USER}
          -e BROWNIE_ATELIER_MONGO__MONGO_PASS=${BROWNIE_ATELIER_MONGO__MONGO_PASS}
          mongo:${MONGO_TAG}

      - run: docker ps -a

      # "🍏 This job's status is success."
      - run: echo "🍏 実行後のステータス： ${{ job.status }}."
