name: Moto
run-name: moto
on:
  workflow_dispatch:

jobs:
  moto_job:
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - run: echo "呼び出し元"
      - name: リポジトリ(${{ github.repository }})・ブランチ(${{ github.ref }})にチェックアウト
      # 上記のリポジトリ・ブランチにチェックアウト
        uses: actions/checkout@v4
      - run: ${{ secrets.BROWNIE_ATELIER_NOTICE__FROM_EMAIL }}

  reuse-job:
    needs: moto_job
    uses: ./.github/workflows/saki.yml
    
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}


