name: Moto
run-name: moto
on:
  workflow_dispatch:

jobs:
  moto_job:
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - run: echo "呼び出し元"
      - name: リポジトリ(${{ github.repository }})・ブランチ(${{ github.ref }})にチェックアウト
      # 上記のリポジトリ・ブランチにチェックアウト
        uses: actions/checkout@v4

  reuse-job:
    needs: moto_job
    uses: ./.github/workflows/saki.yml
    with:
      config-path: "/tmp"
    secrets:
      token: ${{ secrets.REPO_ENV_TEST }}
    # secrets: inherit # pass all secrets

